/**********************************************************************************************************************
 * \file Buzzer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include"UltraBuzzer.h"
#include "Ultrasonic.h" // 부저 테스트 해보기
int UltraBuzzer(void)
{

    my_printf("start\n");

        float distance = Ultrasonic_ReadSensor_noFilt();
        //float distance2 = Ultrasonic_ReadRightSensor_noFilt();
        //float distance3 = Ultrasonic_ReadLeftSensor_noFilt();

        my_printf("Distance rear: %.2f cm\n", distance);
        delay_ms(100);
        //my_printf("Distance left: %.2f cm\n", distance3);
        delay_ms(100);
        //my_printf("Distance right: %.2f cm\n", distance2);
        delay_ms(1000);
        if (distance < 0) {
        // 측정 실패 시 버저 OFF
            setBeepCycle(0);
            return 0;
        }

        if (distance > 30.0f) {
            setBeepCycle(0);  // 30cm 이상: 무음
        }
        else if (distance > 15.0f) {
            setBeepCycle(260);  // 15~30cm: 느린 비프 (6 토글 on/off)
        }
        else if (distance > 5.0f) {
            setBeepCycle(50);  // 5~15cm: 중간속도 비프
        }
        else {
            setBeepCycle(10);  // 5cm 이하: 빠른 비프 (최대로 빠른 깜빡임)
            delay_ms(100);
            //Motor_stopChA();
            //Motor_stopChB();
        }

    return 0;
}
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
