/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "main.h"
#include <stdio.h>
#include <string.h>
IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
float32 distance;

volatile float right_distance __attribute__((section(".lmu_data"))) = 0.0f;
volatile float left_distance  __attribute__((section(".lmu_data"))) = 0.0f;
volatile float rear_distance  __attribute__((section(".lmu_data"))) = 0.0f;
volatile IfxCpu_mutexLock distLock __attribute__((section(".lmu_data"))) = 0;


void core0_main(void)
{
    SYSTEM_Init();
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
//
//    /* Wait for CPU sync event */
//    IfxCpu_emitEvent(&g_cpuSyncEvent);
    
    //
    while(1)
    {
        Asclin1_PollCMD();
//        //UltraBuzzer();
//        setLedCycle(400);
//        setLightButton(1);
//        setLightButton(2);
//        setLightButton(3);
//        delay_ms(100);
//        //my_printf("ditance : %f cm\n", distance);


    }
}



IFX_INTERRUPT(CanRxHandler, 0, ISR_PRIORITY_CAN_RX);
void CanRxHandler (void)
{
    unsigned int rxID;
    unsigned char rxData[8] = {0, };
    int rxLen;
    Can_RecvMsg(&rxID, rxData, &rxLen);

    if (rxID == 0x12)
    {
        //TODO : Vision CAN Frame 구성 및 logic 처리 논의
        my_printf("%s\n", rxData);
    }
    else
    {
        unsigned int tofValue = rxData[2] << 16 | rxData[1] << 8 | rxData[0];
        unsigned char dis_status = rxData[3];
        unsigned short signal_strength = rxData[5] << 8 | rxData[4];

        if (signal_strength != 0)
        {
            if (tofValue <= 100)
            {
                Motor_stopChA();
                Motor_stopChB();
                front_duty = 30;
                back_duty = 30;

                //긴급 제동 Debugging용
                //TODO : 상세 로직
                Motor_movChA_PWM(front_duty, 0);
                Motor_movChB_PWM(back_duty, 0);
                delay_ms(500);
            }
        }
    }

}

