/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "main.h"
#include <stdio.h>
#include <string.h>
#include "ToF.h"
#include "Emergency_stop.h"
//extern unsigned int g_TofValue;
IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
extern v;
void core0_main(void)
{
    SYSTEM_Init();

    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /*// 테스트용 : 좌측 방향지시등만 켜기
    setLedCycle(16000); // 여기서 이제 지시등- 깜빡이별 토글 속도 다르게 할 수도 있음.
    setLeftTurn(1);
    setRightTurn(0);
    setHazzardLight(1);
    /*123*/
    Motor_movChA_PWM(50, 1);
    Motor_movChB_PWM(50, 1);

    while(1)
    {

        float v = velocity();
        int b = Braking_Distance(v);
        my_printf("PWM:50 Deceleration_rate: 1\n");
        my_printf("braking distance : %d\n", b);//v 안에 안갇혀있으니, v값이 들어왔을떄만 코드가 돌아가도록해라.
        my_printf(": %fm/s\n", v);
        Emergency_stop();
        /*
        if (Tof_GetValue() > 100 +b ){
            Motor_movChA_PWM(50, 1);
            Motor_movChB_PWM(50, 1);//0.65~0.75
//

        }
        else {
            my_printf("tof distance: %d\n",Tof_GetValue());
            Motor_stopChA();
            Motor_stopChB();
            my_printf("stop");//
            //Motor_movChA_PWM(30, 0);
            //Motor_movChB_PWM(30, 0);//
            //delay_ms(100);




        }
*/


         // tof 몇일때 멈춰라. 멈췄을 때의 실제 거리 측정. tof-멈춘거리 =  제동거리. - 실험적 측정


    }
}
