/**********************************************************************************************************************
 * \file Drive.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Drive.h"

unsigned int front_duty = 30;
unsigned int back_duty =30;

volatile char asclin_cmd_buffer[ASCLIN_CMD_BUF_SZ];
volatile int asclin_cmd_index = 0;
volatile int asclin_cmd_ready = 0;
int AEB_flag = 0;
char Asclin1_InUartNonBlock(void)
{
    unsigned char ch = 0;
    int res = Asclin1_PollUart(&ch);

    return res == 1 ? ch : -1;
}

void Asclin1_PollCMD(void){
    if(!asclin_cmd_ready) return;
    asclin_cmd_ready=0;

    //default set
    int x= 0;
    int y = 0;
    int swL = 0;
    int swR = 0;
    int swP = 0;
    int dir = 1;

    int check_sum = sscanf((char*)asclin_cmd_buffer, "%d;%d;%d;%d;%d;%d", &x,&y,&swL,&swR,&swP,&dir);

    if(check_sum == 6){
        Motor_Control_CMD(x,y,swL,swR,swP,dir);
        //my_printf("x:%\n y:%c\n swL:%c\n swR:%c\n swP:%c\n dir:%c", x,y,swL,swR,swP,dir);
    }
    else{//for debugging
        my_printf("파싱 실패...");
    }
}

IFX_INTERRUPT(BLEIsrHandler,0,ISR_PRIORITY_BLE_RX);
void BLEIsrHandler (void)
{
    __enable();

    unsigned char ch;
    if(Asclin1_PollUart(&ch)){
        if(ch == '\n' || ch =='\r'){
            if(asclin_cmd_index>0){
                asclin_cmd_buffer[asclin_cmd_index]='\0'; //c-style 처리
                asclin_cmd_ready = 1; //flag
                asclin_cmd_index = 0; //index pointer reset
            }
        }
        else if(asclin_cmd_index < ASCLIN_CMD_BUF_SZ -1){ //여기서 채워요
            asclin_cmd_buffer[asclin_cmd_index++]= ch;
        }
        else{
            asclin_cmd_index=0; // 완성안되면 buffer flush(실제 flush는 아님)
        }

   }
}

void Motor_Control_CMD (int x, int y, int swL, int swR, int swP, int dir)
{
    my_printf("left: %d\n", x);
    my_printf("right: %d\n", y);
    my_printf("dir: %d\n",dir);

    // Backward
    if (dir == 0)
    {
        Motor_movChA_PWM(x, 0);
        Motor_movChB_PWM(y, 0);
    }

    //Forward
    else
    {
        if (!AEB_flag)
        {
            Motor_movChA_PWM(x, 1);
            Motor_movChB_PWM(y, 1);
        }
    }

    //TODO : Switch 처리 및 추가 및 응집도 결합도 Fan-IN/Fan-OUT 고려해 Module화 진행 예정

}



/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
